[theme]

[theme]

primaryColor="#d33682"
backgroundColor="#002b36"
secondaryBackgroundColor="#586e75"
textColor="#fafafa"
font="sans serif"

# Primary accent for interactive elements
# primaryColor = '#fff'

# Background color for the main content area
# backgroundColor = '#000'

# Background color for sidebar and most interactive widgets
# secondaryBackgroundColor = '#000'

# Color used for almost all text
# textColor = '#fff'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
# font = "sans serif"