class Exchange:
    def __init__(self, 
                idcashflow, 
                fk_idcompany, 
                idchartaccounts, 
                fk_idcustomer, 
                customer_phone, 
                fk_idtypeproduct, 
                fk_idproduct, 
                fk_idbankmaster, 
                fk_idbankclient, 
                fk_idchartaccounts, 
                dtcashflow, 
                tchaflow, 
                amountflow, 
                valueflow, 
                valuewire,
                centsflow, 
                cents2flow, check_number, percentflow, 
                valuepercentflow, 
                airpercentflow, 
                aircomisvalue, 
                airreservation, 
                airdtemiuntil, 
                totalflow, 
                movetype, 
                totaltopay, 
                cashflowok, 
                cashflowobs, 
                cashfloworigin, 
                wire, 
                subtotalflow, 
                idlogin, 
                vin, 
                fk_idcountry, 
                fk_idmaker, 
                year, 
                model, 
                fk_idcoverage, 
                description,
                fk_idstore
        ):
        self.idcashflow = idcashflow, 
        self.fk_idcompany = fk_idcompany, 
        self.idchartaccounts = idchartaccounts, 
        self.fk_idcustomer = fk_idcustomer, 
        self.customer_phone = customer_phone, 
        self.fk_idtypeproduct = fk_idtypeproduct, 
        self.fk_idproduct = fk_idproduct, 
        self.fk_idbankmaster = fk_idbankmaster, 
        self.fk_idbankclient = fk_idbankclient, 
        self.fk_idchartaccounts = fk_idchartaccounts, 
        self.dtcashflow = dtcashflow, 
        self.tchaflow = tchaflow, 
        self.amountflow = amountflow, 
        self.valueflow = valueflow, 
        self.valuewire = valuewire,
        self.centsflow = centsflow, 
        self.cents2flow = cents2flow, 
        self.check_number = check_number, 
        self.percentflow = percentflow, 
        self.valuepercentflow = valuepercentflow, 
        self.airpercentflow = airpercentflow, 
        self.aircomisvalue = aircomisvalue, 
        self.airreservation = airreservation, 
        self.airdtemiuntil = airdtemiuntil, 
        self.totalflow = totalflow, 
        self.movetype = movetype, 
        self.totaltopay = totaltopay, 
        self.cashflowok = cashflowok,
        self.cashflowobs = cashflowobs,
        self.cashfloworigin = cashfloworigin,
        self.wire = wire,
        self.subtotalflow = subtotalflow,
        self.idlogin = idlogin,
        self.vin = vin,
        self.fk_idcountry = fk_idcountry,
        self.fk_idmaker = fk_idmaker,
        self.year = year,
        self.model = model,
        self.fk_idcoverage = fk_idcoverage,
        self.description = description,
        self.fk_idstore = fk_idstore
